### PR TITLE
Lossless compression

### PR DESCRIPTION
**Pull request by MathiasReker**
More to come, but I have to do it in another PR's because it takes a lot of time to make lossless compression.

### CODE REVIEW

**Comment by hailite** [comment]
For this PR, please slack @mark who is our designer that is in charge of all photographs. Need his approval on this. About screenshot, please don't include in PR. they will be upgraded in v3.0.

**Comment by MathiasReker** [comment]
Maybe I should rather run my script on next version? I use 17 libraries to compress the images lossless.

**Comment by hailite** [comment]
i pinged you on slack but no response.

**Comment by MathiasReker** [comment]
I am online now

**Pull request closed without merging**
