### PR TITLE
Update css_excludes.txt

### PR DESCRIPTION
**Pull request by qtwrk**

### CODE REVIEW

**Comment by hi-hai** [comment]
Please comment which plugin this is for.

**Comment by hi-hai** [comment]
@qtwrk if we use this, `#text-box-` should be removed?

**Comment by qtwrk** [comment]
yes

**Comment by hi-hai** [comment]
Have to create new commit as this can't be updated. https://github.com/litespeedtech/lscache_wp/commit/b5a579c43433c97ff4605975a12125f70b3b9cd6

**Pull request closed without merging**
