### PR TITLE
Short array syntax

### PR DESCRIPTION
**Pull request by MathiasReker**

### CODE REVIEW

**Comment by hailite** [comment]
Not Compatible with PHP 5.3

**Comment by MathiasReker** [comment]
Sorry, I did not pay attention to that. I made my PR's to be PHP 5.6+

**Comment by hailite** [comment]
Thanks for your PR. Please join our golitespeed slack for further PR and better improvements to LSCWP. Appreciated.

**Comment by MathiasReker** [comment]
I am already on your slack :)

**Pull request closed without merging**
