### PR TITLE
Purge actions and filter

### PR DESCRIPTION
**Pull request by timotei-litespeed**
Add filters for post purge events
Add actions for each major purge event

Changes are done to help users add their own actions and functionalities.
Example most recent: [https://wordpress.org/support/topic/delete-entry-cache-when-saving/#post-18106071](https://wordpress.org/support/topic/delete-entry-cache-when-saving/#post-18106071)

### CODE REVIEW

**Comment by hi-hai** [comment]
The filter part is fine. Why do we need to add those many actions? @timotei-litespeed

**Comment by timotei-litespeed** [comment]
@hi-hai to allow users add custom code to run after different purge actions

**Comment by hi-hai** [comment]
Can u use dev to commit again? We froze v7.0 branch already

**Comment by timotei-litespeed** [comment]
done #776

**Pull request closed without merging**
