### PR TITLE
Check filename is valid or not

### PR DESCRIPTION
**Pull request by AkramiPro**
in some cases, filename is null and fire PHP warning on `direname` function.

### CODE REVIEW

**Comment by timotei-litespeed** [comment]
Thank you for the fix. We will review it and decide what will happen to it.

One thing that will help us: is to give details of when the warning appears. What action(s) you do for the warning to appear.

Tim

**Comment by AkramiPro** [comment]
I should mention that this is just a quick fix for suppress PHP warning.
in fact, we have no debug functionality when using object cache and it must be fixed.
`Debug2` class needs to be changed to support headless running without any dependency on core.

**Comment by timotei-litespeed** [comment]
You are right about just hidding it, that's why I asked you about the error.
What is the version of the plugin you see the warning?

**Comment by AkramiPro** [comment]
set this in wp-config.php
```
define( 'LSCWP_LOG', true );
```

**Comment by timotei-litespeed** [comment]
Ok, that makes sense :)
LSCWP_LOG is not made to be used like that.
Why do you added the LSCWP_LOG in wp-config?

I will look over the Debug class to remove the warning in this case.
Thank you for your details! :)

**Comment by AkramiPro** [comment]
yes, you are right. i look at the source and to force object cache create logs make some changes and forgot that  LSCWP_LOG  must not set manually.
anyway, check for filename is always a good practice :)

**Comment by timotei-litespeed** [comment]
@hi-hai 
As per above findings our code will not throw error.
There is the possibility of user defining `define( 'LSCWP_LOG', true );` in wp-config.php and that will show errors when object cache is activated.
PR goal is to remove the warnings that will appear when dirname from `File::save()` will get incorrect filename.

**Comment by timotei-litespeed** [comment]
@AkramiPro thank you for the informations and we will further decide what is the correct action on the situation you described

**Comment by hi-hai** [comment]
> yes, you are right. i look at the source and to force object cache create logs make some changes and forgot that LSCWP_LOG must not set manually. anyway, check for filename is always a good practice :)

That makes sense. Added in https://github.com/litespeedtech/lscache_wp/commit/6e79c5c919a789dce6c46294934707d389dfce2a. Thanks.

**Comment by timotei-litespeed** [comment]
@AkramiPro 👍

**Pull request closed without merging**
