### PR TITLE
String Fixes

### PR DESCRIPTION
**Pull request by garrett-eclipse**

### CODE REVIEW

**Comment by garrett-eclipse** [comment]
No worries can drop that commit, was just trying to be consistent as it's Privacy Policy throughout the rest of the readme and site. Let me know if you want me to drop taht commit

**Comment by hailite** [comment]
Well just operated by mistake. Can you send a new pull request? Thanks.

**Comment by hailite** [comment]
Included in https://github.com/litespeedtech/lscache_wp/commit/69dc719d4f92056c6356e6fc5bbc8486bffd29a0

Thanks.

**Comment by garrett-eclipse** [comment]
Thanks @hailite let me know if there's anything you need from me here

**Pull request merged**
