### PR TITLE
bypass js optm if data-cfasync="false"

### PR DESCRIPTION
**Pull request by qtwrk**

### CODE REVIEW

**Comment by galbaras** [comment]
Any idea when this will be merged? Once it is, I can start using the plugin and you can boast plugin and Cloudflare compatibility.

**Comment by galbaras** [comment]
This really seems like an easy win. Any reason for not releasing it?

**Comment by hi-hai** [comment]
@galbaras Do you have any idea which plugin added that attribute?

**Comment by galbaras** [comment]
Several popular plugins add this attribute to their scripts, like MonsterInsights and EWWW Image Optimizer, but it can also be added in themes or via filters, etc.

Why would you not do it? This attribute means that the script developer wanted it skipped by the Cloudflare page optimiser, which implies ANY page optimiser.

When I suggested it to the developer of WP Fastest Cache, he added it, I tested it, and he released it, so now sites using that plugin for optimisation run more correctly, even if they load slightly more slowly.

**Comment by hi-hai** [comment]
This makes sense. Thanks for explanation.

**Comment by galbaras** [comment]
When will this be released?

**Comment by galbaras** [comment]
Has this been released yet?

**Pull request merged**
