### PR TITLE
Fix undefined warning

### PR DESCRIPTION
**Pull request by timotei-litespeed**
Fix warning reported: https://github.com/litespeedtech/lscache_wp/issues/713

### CODE REVIEW

**Comment by szepeviktor** [comment]
`global` should be at the top of a function.

**Comment by timotei-litespeed** [comment]
Yes, fixed :)
thx @szepeviktor

**Comment by szepeviktor** [comment]
You're welcome.

**Comment by hi-hai** [comment]
This commit involved non-related code change. Please start a new one and always go through your changes in PR to make sure they are expected changes ONLY.

**Pull request closed without merging**
