### PR TITLE
Space after semicolon

### PR DESCRIPTION
**Pull request by MathiasReker**

### CODE REVIEW

**Comment by hailite** [comment]
Can approve but may cause conflicts with current v3.0 refactoring. Will leave after v3.0 release.

**Comment by MathiasReker** [comment]
Do you want be to rebuild all PR's on v3.0 branch?

**Comment by hailite** [comment]
We are still having lots of changing in v3.0. Yes but this is not the right time for that. Could be done after v3.0 release. Thanks.

You are always welcome to talk to us directly on slack for further improvements.

**Comment by MathiasReker** [comment]
You are welcome to ping me anytime, if you wish me to rebuild those PR's. I wrote a shell script to make the PR's so I can easily remake the PR's.

**Comment by hi-hai** [comment]
Same as https://github.com/litespeedtech/lscache_wp/pull/113#issuecomment-868581007

**Pull request closed without merging**
