### PR TITLE
MetForm: Added nonce field for form submissions to prevent caching

### PR DESCRIPTION
**Pull request by sharif-xs**

### CODE REVIEW

**Comment by hi-hai** [comment]
Have you tested this change?

**Comment by sharif-xs** [comment]
Yes, @hi-hai

**Comment by hi-hai** [comment]
Thanks for your PR. 

However, you can see in the 1st line of data/esi.nonce.txt it stated this file is a legacy file which won't affect new versions. You may need to verify again if the change works or not in your testing.

**Comment by sharif-xs** [comment]
Hi, @hi-hai 

Then, is this the correct file for the new version https://github.com/litespeedtech/lscache_wp/blob/master/data/esi.nonces.txt ?

Thanks

**Comment by hi-hai** [comment]
Do you mind to tell the test process so we can make sure what you changed did work?

**Comment by sharif-xs** [comment]
Sure,

Step 1: Install the MetForm plugin,
Step 2: Create a form with Metform ([](https://www.youtube.com/watch?v=zg1QIouKO_Q&t=48s))
Step 3: Submit the form (make sure to enable the lite speed cache)
Step 4: Re-Submitting form after expiring the nonce (By default, WordPress' NONCEs expire 24 hours after they have been created. In that case you can expire it manually)
Step 5: Usually, the form will not submit cause nonce verification will fail but if you check with this PR then it should work.

Still, if you have any confusion please let me know.

Thank you.

**Comment by hi-hai** [comment]
Those are correct steps to test. Good job! However, you also need to test the patch. W/ the original commit, it shouldn't fix the issue IMO.

**Comment by sharif-xs** [comment]
Sorry, I couldn't understand the 'original commit' as you said in that last message.

Could you please elaborate it?

Thank you

**Comment by hi-hai** [comment]
https://github.com/litespeedtech/lscache_wp/pull/649/commits/bb4137fd7505b09ef97117e1e9b204fe59ff68f0
I meant this one.

You reproduced the issue, that is great. However it seems you missed testing the patch to make sure that does fix the issue?

**Comment by sharif-xs** [comment]
Hi @hi-hai ,

Before that, I have a question and confusion. As '\data\esi.nonce.txt' is the legacy file then should I add my code in the '\data\esi.nonces.txt' file?

Thank you

**Comment by hi-hai** [comment]
> Hi @hi-hai ,
> 
> Before that, I have a question and confusion. As '\data\esi.nonce.txt' is the legacy file then should I add my code in the '\data\esi.nonces.txt' file?
> 
> Thank you

Yes

**Comment by sharif-xs** [comment]
Thank you very much! for confirming @hi-hai 

Added the code in the latest file and updated the PR.

Regards

**Comment by hi-hai** [comment]
Could you kindly advise it passed your testing or not?

**Comment by sharif-xs** [comment]
Yes, It's working fine.

Thank you

**Comment by hi-hai** [comment]
Good job! Thanks for your contribution.

**Comment by sharif-xs** [comment]
It's my pleasure!

Thank you

**Pull request merged**
