### PR TITLE
Update instant_click.min.js

### PR DESCRIPTION
**Pull request by Tymotey**
Ticket: #802070 - LSCWP: Cookiebanners not working after upgrade
Problem: Cookie banners(with plugin "Cookie Information - Consent Solution") were not loading

Solution: instant click library(minified version) have the same variables with  "Cookie Information - Consent Solution". I minified the library with different variable names.

### CODE REVIEW

**Comment by hi-hai** [comment]
This PR can't be reviewed. Plz update the original JS.

**Comment by szepeviktor** [comment]
> the original JS.

https://github.com/litespeedtech/lscache_wp/blob/v6.4/assets/js/instant_click.ori.js

**Comment by timotei-litespeed** [comment]
There are no changes into the library.
I just used instant_click from our plugin to rerun the minification.
Everything is the same except variable names

**Comment by hi-hai** [comment]
Need to add a note for this change as hard to review diff:
Used https://www.toptal.com/developers/javascript-minifier to optimize original JS lib.

**Pull request merged**
